server:
  port: 8005

spring:
  application:
    name: mango-consumer
  boot:
    admin:
      client:
        url: "http://localhost:8000"
service-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#开启熔断器
feign:
  hystrix:
    enabled: true
